version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=la-chaise-du-savoir
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/la-chaise-du-savoir"
volumes:
  db_data:
