services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=la-chaise-du-savoir
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lcds-network

  back:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/la-chaise-du-savoir"
    networks:
      - lcds-network

  front:
    build: ../la-chaise-du-savoir-front
    ports:
      - "3000:3000"
    environment:
        - "NEXT_PUBLIC_API_BASE_URL=http://back:8080/api"
    networks:
      - lcds-network

networks:
  lcds-network:
    name: lcds-network
    driver: bridge

volumes:
  db_data:
